feat: Add aliases and functions for podman and docker commands

diff --git a/flavors/cinnamon/home/_bash_functions b/flavors/cinnamon/home/_bash_functions
--- a/flavors/cinnamon/home/_bash_functions
+++ b/flavors/cinnamon/home/_bash_functions
@@ -6,13 +6,13 @@ background() {
 # chown me all files in dir
 reown() {
   GROUP=$(id -gn)
-  # find . -path ./tmp -prune -o \! -user $USER -exec sudo chown $USER:$GROUP -v {} \;
-  find . -not -path "*/node_modules/*" -not -path "*/logs/*" -not -path "*/tmp/*" -not -user $USER -exec sudo chown $USER:$GROUP -v {} \;
+  find . -not -user $USER -exec sudo chown $USER:$GROUP -v {} \;
 }
 
 backup() {
-  FILENAME=$(pwd | rev | cut -d "/" -f 1 | rev)
-  tar -cjvf ../backup-$FILENAME-`date +"%F"`.tar.bz2 --exclude .git --exclude tmp --exclude logs  --exclude log .
+  FILENAME=$(basename $(pwd))
+  tar -cjvf ../backup-$FILENAME-`date +"%F"`.tar.bz2 --exclude .git --exclude logs  --exclude log .
+  echo Created new backup $BACKUP_NAME
 }
 
 md5_rename() {
@@ -38,4 +38,51 @@ md5_rename() {
             mv -v "$filename" "${filehash}.${fileext}"
         fi
     done
+}
+
+# force all running containers to stop
+podman-stall() {
+  podman ps -q | xargs podman stop
+}
+
+# create a tunnel
+mytunnel() {
+  if [ -z "$1" ] || ! [[ "$1" =~ ^[0-9]+$ ]]; then
+    echo "Invalid PORT argument!"
+    echo "Usage: mytunnel PORT [-v]"
+    return 1
+  fi
+
+  local_port=$1
+  verbose=""
+
+  shift
+
+  while getopts ":v" opt; do
+    case ${opt} in
+      v)
+        verbose="-v"
+        ;;
+      \?)
+        echo "Invalid option: -$OPTARG" 1>&2
+        echo "Usage: mytunnel PORT [-v]"
+        return 1
+        ;;
+    esac
+  done
+  shift $((OPTIND -1))
+
+  nc -z localhost $local_port
+  if [ $? -ne 0 ] ; then
+   echo "Fail to connect to port localhost:$local_port"
+   return 1
+  fi
+
+  echo "Redirecting localhost:$local_port to https://mytunnel.ddns.net"
+  ssh $verbose -N -o ServerAliveInterval=20 -R 8000:localhost:$local_port mytunnel.ddns.net
+}
+
+# clean all __pycache__ dirs (recursive)
+pyclean() {
+  find . -type d -name __pycache__ -exec rm -rf {} \;
 }
